### ISSUE TITLE
Bug: tox lint commands reports warnings

### ISSUE THREAD

**Issue by joshuagl** [vmware/repository-service-tuf-api#237] opened 2023-01-25 14:38 UTC
### What happened?

The output of the lint checks, i.e. https://github.com/vmware/repository-service-tuf-api/pull/235/checks#step:5:65 , includes several warnings about the use of a glob matching pattern.

### What behavior did you expect?

Only warnings or errors introduced by a PR are reported in the checks output.

### Relevant log output

```shell
> Warning:  The 'exclude' field in hook 'flake8' is a regex, not a glob -- matching '/*' probably isn't what you want here
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by KAUTH** [comment] 2023-02-01 11:54
Hey @joshuagl, thanks for pointing this out. ☺️ I believe this is not a bug.

This warning was added to `pre-commit` in [this](https://github.com/pre-commit/pre-commit/issues/1702) issue. `pre-commit` expects in `exclude` a python regular expressions matched with `re.search` (see [here](https://pre-commit.com/#regular-expressions)).

Basically, in our use-case this warning is triggered from the inclusion of `/*lib/python*|/*egg` (the `/` specifically) in the `exclude` section. What we want to achieve with this is, for `flake8` in this case, to not get the files that match this expression passed to it.

If we omitted the `/` we would get a `TypeError("first argument must be string or compiled pattern")`.

You can verify that the match works ([here](https://github.com/pre-commit/pre-commit/blob/59ed51a309565dd999ea0af8cc1f0cecf1a9f04a/pre_commit/commands/run.py#L68) is where `pre-commit` does it) by testing with this:

```python
import re

def test_file_regex(regex, filename):
     pattern = re.compile(regex)
     print(pattern.search(filename))

test_file_regex("/*egg"", "asdfegg")  # <re.Match object; span=(4, 7), match='egg'>
```

These exclusion were adapted from the `flake8` configuration (`repository_service_tuf/__init__.py,venv,.venv,settings.py,.git,.tox,dist,docs,*lib/python*,*egg,build,tools`) we used to have and `flake8` uses glob patterns (see [here](https://flake8.pycqa.org/en/latest/user/options.html#cmdoption-flake8-exclude))
What I do see we can do as an improvement is specify the regex's start/ending, for example, `/*egg$`, otherwise, `asdfeggother` also matches. This could be done for all patterns.
(@kairoaraujo, @MVrachev what do you think?)

**Comment by joshuagl** [comment] 2023-02-01 12:22
Thanks for the detailed response. So is there a mismatch here? As far as I understand your writeup, the pre-commit framework expects exclude patterns to be in regular expression format, whereas flake8 expects exclude patterns to be in glob format. 

This is causing errors to be surfaced when a glob format exclude is passed to a tool expecting a regular expression formatted exclude pattern. Is that right?

**Comment by KAUTH** [comment] 2023-02-01 22:03
> This is causing errors to be surfaced when a glob format exclude is passed to a tool expecting a regular expression formatted exclude pattern. Is that right?

Not exactly, by excluding files in `pre-commit` they are never passed to `flake8` for linting, which is what we want. We just have to take into account that `pre-commit` expects a regular expression format.
What we have now works, but it's not the exact match of what we used to have in the `flake8` formatted exclude.

Example:
`flake8`: `settings.py` - this means that only the file `settings.py` will be excluded (what we used to have in `tox.ini`'s `flake8` config)
`pre-commit`: `settings.py` - this means that the file `settings.py` but also a file name `test-setting.py` will be excluded.
If we want to have a more precise match we should change it to: `^settings.py$`

**Comment by MVrachev** [comment] 2023-02-02 12:43
If we have a precise idea of what we want to exclude I am okay to clarify the regex.
Honestly, I didn't understand does `pre-commit` successfully exclude the files we want or not. Are there files we miss now?
The example was not very clear to me.

**Comment by KAUTH** [comment] 2023-02-07 19:54
> This is causing errors to be surfaced when a glob format exclude is passed to a tool expecting a regular expression formatted exclude pattern. Is that right?

Not exactly, by excluding files in `pre-commit` they are never passed to `flake8` for linting, which is what we want. We just have to take into account that `pre-commit` expects a regular expression format.
What we have now works, but it's not the exact match of what we used to have in the `flake8` formatted exclude.

Example:
`flake8`: `settings.py` - this means that only the file `settings.py` will be excluded (what we used to have in `tox.ini`'s `flake8` config)
`pre-commit`: `settings.py` - this means that the file `settings.py` but also a file name `test-setting.py` will be excluded.
If we want to have a more precise match we should change it to: `^settings.py$`

**Comment by KAUTH** [comment] 2023-02-07 21:29
AFAIK we are not missing files, but as mentioned above, the `exclude` in `.pre-commit-config.yaml` expects a regular expression format (that will be matched with `re.search`). So, for example, adding `settings.py` to the list will not only exclude the file named `settings.py`, but would also exclude a file named, e.g., `test-setting.py`.

**Comment by MVrachev** [comment] 2023-02-08 09:56
I understand.
If you want to spend time on this so we can properly exclude folders I support it.

On the topic of excluding folders: I was thinking that instead of excluding folders why don't we include the ones we want to lint?
They are not many top-level folders and this will make it easier for us to add new configuration files or other meta folders.
@kairoaraujo do you have any opinion on this?

**Comment by kairoaraujo** [comment] 2023-02-08 14:39
> I see. If you want to spend time on this so we can properly exclude folders I support it.

+1 it is not a hurry to close this issue. Even if @KAUTH doesn't want to work on it we can add it as a task for this issue to be closed.

> On the topic of excluding folders: I was thinking that instead of excluding folders why don't we include the ones we want to lint? They are not many top-level folders and this will make it easier for us to add new configuration files or other meta folders. @kairoaraujo do you have any opinion on this?

The excluding is more safety.
If we introduce a new folder and don't add it to the included list, it can take a long time until we notice that.

**Comment by KAUTH** [comment] 2023-02-08 22:29
> The excluding is more safety.
If we introduce a new folder and don't add it to the included list, it can take a long time until we notice that.

I would go this way as well

**Closed** 2023-03-10 17:58 UTC
Labels: bug
